language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=1.6.7
  - DJANGO=1.7
install:
  - pip install Django==$DJANGO
  - pip install "file://`pwd`#egg=django-crispy-forms[tests]"
  - pip install -e . --use-mirrors
script:
  - make test
notifications:
  email: false
